source('http://www.bioconductor.org/biocLite.R') 
biocLite ("hgu95av2cdf") 
require(hgu95av2cdf) 
biocLite ("hgu95av2probe") 
require(hgu95av2probe) 
# setwd("Asiakirjat/temp/htb/")
biocLite("affy")
require(affy)
biocLite("affydata")
require(affydata)
source("customCDF.R")
